import { motion } from 'framer-motion'
import { Terminal, Check, Volume2, ShieldAlert } from 'lucide-react'
import { DAY_PLAN_TASKS, VOICE_NARRATION } from '../data/agents'

const listContainerVariants = {
  hidden: { opacity: 0 },
  show: {
    opacity: 1,
    transition: {
      staggerChildren: 0.1,
      delayChildren: 0.2
    }
  }
}

const taskItemVariants = {
  hidden: { opacity: 0, x: -20 },
  show: {
    opacity: 1,
    x: 0,
    transition: { duration: 0.4, ease: [0.16, 1, 0.3, 1] }
  }
}

export default function DayPlanOutput({ tasks = DAY_PLAN_TASKS, voiceNarration = VOICE_NARRATION, speechActive, onPlay, onStop }) {
  return (
    <div className="day-plan-card glass-panel pulse-glow">
      <div className="day-plan-header">
        <Terminal size={24} className="day-plan-header-icon text-[#0EA5E9]" />
        <div className="day-plan-title">
          <h3>Incident Remediation Runbook</h3>
          <p>Generated by SeedheOps 5-agent swarm · All execution commands sequenced</p>
        </div>
      </div>

      <motion.div
        className="tasks-timeline"
        variants={listContainerVariants}
        initial="hidden"
        animate="show"
      >
        {tasks.map((task, index) => (
          <motion.div
            key={task.time || index}
            className="task-item"
            variants={taskItemVariants}
          >
            <div className="task-time-pill">{task.time}</div>
            <div className="task-detail">
              <strong>{task.title}</strong>
              <code className="task-cmd-code block mt-1.5 text-xs font-mono text-emerald-400 bg-black/50 px-2.5 py-1.5 rounded border border-emerald-500/20 break-all select-all">
                $ {task.description}
              </code>
            </div>
            <div className="task-status-badge">
              <Check size={12} />
              <span>{task.status}</span>
            </div>
          </motion.div>
        ))}
      </motion.div>

      {/* Audio Sitrep Button */}
      <div className="flex flex-col gap-3 mt-6">
        <button
          type="button"
          className={`speak-plan-btn ${speechActive ? 'active' : ''}`}
          onClick={speechActive ? onStop : onPlay}
        >
          <Volume2 size={16} color="rgba(255, 255, 255, 0.85)" />
          <span>{speechActive ? 'Stop Audio Sitrep' : 'Play Audio Sitrep'}</span>
          {speechActive && <span className="speak-status-dot" />}
        </button>

        <button
          type="button"
          className="speak-plan-btn secondary-voice-btn"
          onClick={() => {
            alert("🎙️ SeedheOps Voice Sitrep Stream active!")
          }}
        >
          <Volume2 size={16} color="rgba(255, 255, 255, 0.75)" />
          <span>Synthesize Audio Sitrep</span>
        </button>

        <div className="voice-preview-box">
          <p className="voice-text">
            &ldquo;{voiceNarration}&rdquo;
          </p>
        </div>
      </div>
    </div>
  )
}
